train:
  model_family: surrogate
  use_wavelet_weights: false
paths:
  h5:
    train:
      h5_path: /scratch/project_2008261/pf_surrogate_modelling/data/stochastic/rightclean/simulation_train_rightclean_fixed34_gradshared.h5
      weight_h5: null
    val: /scratch/project_2008261/pf_surrogate_modelling/data/stochastic/rightclean/simulation_val_rightclean_fixed34_gradshared.h5
  sim_map: /scratch/project_2008261/pf_surrogate_modelling/data/stochastic/sim_map.json
dataloader:
  file: /scratch/project_2008261/pf_surrogate_modelling/models/train/core/pf_dataloader.py
  class: PFPairDataset
  args:
    input_channels:
    - 0
    - 1
    target_channels:
    - 0
    - 1
    identity_pairs: true
    use_pairs_idx: false
    add_thermal: false
    return_cond: false
    normalize_images: true
    normalize_force: false
    normalize_source: file
  train_args:
    limit_per_group: null
    max_items: null
    augment: false
    augment_rotate: false
    augment_rotate_prob: 0.0
    augment_flip: false
    augment_swap: false
    augment_roll: false
  val_args:
    limit_per_group: null
    max_items: null
    augment: false
model:
  file: /scratch/project_2008261/pf_surrogate_modelling/models/latent/ae_lola_model.py
  class: LatentAELoLAModel
  params:
    in_channels: 2
    latent_channels: 32
    hid_channels:
    - 64
    - 128
    - 256
    - 512
    - 768
    hid_blocks:
    - 3
    - 3
    - 3
    - 3
    - 3
    stage_strides: null
    dropout: 0.05
    saturate_bound: 5.0
    saturate_kind: softclip2
    identity_init: true
    pixel_shuffle: true
    patch_size: 1
    norm: layer
    ffn_factor: 1
    periodic: y_left_replicate_right_reflect
loss:
  base: vmse
  vmse_eps: 0.01
  weight_wavelet_loss: 0.0
  ae_wavelet:
    enabled: false
    J: 2
    wave: haar
    mode: zero
    lambda_wav: 0.0
    mask_weight: 1.0
    mask_alpha: 999.0
    mask_percentile: 0.93
    mask_warmup_steps: 2000
adaptive:
  region_selector: none
  enable_adaptive_resolution: false
conditioning:
  enabled: false
  cond_dim: 0
  source: field
loader:
  batch_size: 2
  num_workers: 1
  pin_memory: true
trainer:
  seed: 1
  deterministic: true
  device: cuda
  epochs: 500
  steps_per_epoch: null
  nan_debug: false
  nan_debug_steps: 0
  nan_debug_param: autoencoder.encoder.descent.0.0.weight
  nan_tolerate_steps: 3
  lr_warmup_steps: 0
  lr_warmup_start_lr: 0.0
  accumulation_steps: 2
  use_val: true
  out_dir: /scratch/project_2008261/pf_surrogate_modelling/runs/ae_latent_lola_big_64_1024_psgd_uncached_freq1_12g_latent32_nowavelet_rightclean_fixed34_gradshared_b40_precond64_p128
  grad_clip: 0.2
  resume: false
  amp:
    enabled: true
    dtype: fp16
  channels_last: false
  metrics:
    mae: true
    psnr: true
    vrmse: true
    spectral_rmse: true
    spectral_train: false
  early_stop:
    enabled: false
  use_wavelet_weights: false
optim:
  name: psgd
  lr: 1.0e-05
  weight_decay: 0.0
  betas:
  - 0.9
  precondition_frequency: 64
  precondition_frequency_decay: 0.999
  precondition_size: 128
  precondition_warmup: 0
  psgd_cached: false
  psgd_delayed: true
  merge_dims: false
sched:
  name: cosine
  T_max: 500
  eta_min: 1.0e-07
  warmup_epochs: 0
  warmup_start_lr: 0.0
